### ISSUE TITLE
MIN SDK

### ISSUE THREAD

**Issue by paatz04** [sephiroth74/ImageViewZoom#87]
Hi,

what is the latest version that was working with min SDK 15?
I used the gradle dependency "...:+" for a while now but this morning the min SDK was upgraded to 16.

Thank you,
Patric

**Comment by paatz04** [comment]
by the way it's using 2.2.5-SNAPSHOT with the :+ annotation

**Comment by sephiroth74** [comment]
in the recent snasphot (2.2.5) I've removed the support for 14 and 15. You can still use 2.2.4 instead

**Comment by paatz04** [comment]
2.2.4 it is! Perfetto grazie!
