### ISSUE TITLE
minSDK version changed to 16?

### ISSUE THREAD

**Issue by oguzhandongul** [sephiroth74/ImageViewZoom#88]
My application's minSDK version is 15. Your library was working perfectly until yesterday. After last commit I cannot build my application because of the minSDK issue.

At Your library's manifest file it says minSdkVersion="9" but your gradle, it says minSdkVersion="16".

Please fix this. I cannot use minSdkVersion="16" in my app. If you not, I will use another library.

**Comment by oguzhandongul** [comment]
Solved it by using this : 

`dependencies {
compile 'it.sephiroth.android.library.imagezoom:imagezoom:2.2.3-SNAPSHOT'
}`

**Comment by sephiroth74** [comment]
Use version 2.2.4. It's compatible with a api >= 14
